/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Thu Dec 12 22:22:08 2019. */

#ifndef PB_COVERCONFIG_PB_H_INCLUDED
#define PB_COVERCONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CoverConfigMessage {
    uint8_t position;
    uint8_t direction;
    uint8_t hand_pull;
    uint8_t weak_switch;
    uint8_t power_switch;
    uint8_t pin_rx;
    uint8_t pin_tx;
    uint8_t pin_led;
    uint8_t pin_btn;
/* @@protoc_insertion_point(struct:CoverConfigMessage) */
} CoverConfigMessage;

/* Struct field encoding specification for nanopb */
extern const pb_field_t CoverConfigMessage_fields[10];

/* Maximum encoded size of messages (where known) */
#define CoverConfigMessage_size                  58

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COVERCONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
