/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sat Dec 07 20:42:12 2019. */

#include "RelayConfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RelayConfigMessage_fields[11] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, RelayConfigMessage, led_type, led_type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_start, led_type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_end, led_start, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, power_on_state, led_end, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, last_state, power_on_state, 0),
    PB_REPEATED_FIXED_COUNT(  6, UINT32  , OTHER, RelayConfigMessage, study_index, last_state, 0),
    PB_REPEATED_FIXED_COUNT(  7, UINT32  , OTHER, RelayConfigMessage, study, study_index, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_light, study, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_time, led_light, 0),
    PB_FIELD( 20, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, module_type, led_time, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
