/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Thu Dec 12 22:22:08 2019. */

#ifndef PB_WEILECONFIG_PB_H_INCLUDED
#define PB_WEILECONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _WeileConfigMessage {
    uint16_t jog_time;
    uint16_t start_interval;
    uint16_t weile_time;
    uint16_t screen_time;
    uint16_t close_power;
    uint8_t pin_rel;
    uint8_t pin_led;
    uint8_t pin_btn;
/* @@protoc_insertion_point(struct:WeileConfigMessage) */
} WeileConfigMessage;

/* Struct field encoding specification for nanopb */
extern const pb_field_t WeileConfigMessage_fields[9];

/* Maximum encoded size of messages (where known) */
#define WeileConfigMessage_size                  51

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEILECONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
