/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Sat Dec 07 20:42:13 2019. */

#ifndef PB_WEILECONFIG_PB_H_INCLUDED
#define PB_WEILECONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _WeileConfigMessage {
    uint16_t jog_time;
    uint16_t start_interval;
    uint16_t weile_time;
    uint16_t screen_time;
    uint16_t close_power;
    uint8_t pin_rel;
    uint8_t pin_led;
    uint8_t pin_btn;
/* @@protoc_insertion_point(struct:WeileConfigMessage) */
} WeileConfigMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define WeileConfigMessage_init_default          {0, 0, 0, 0, 0, 0, 0, 0}
#define WeileConfigMessage_init_zero             {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WeileConfigMessage_jog_time_tag          1
#define WeileConfigMessage_start_interval_tag    2
#define WeileConfigMessage_weile_time_tag        3
#define WeileConfigMessage_screen_time_tag       4
#define WeileConfigMessage_close_power_tag       5
#define WeileConfigMessage_pin_rel_tag           20
#define WeileConfigMessage_pin_led_tag           21
#define WeileConfigMessage_pin_btn_tag           22

/* Struct field encoding specification for nanopb */
extern const pb_field_t WeileConfigMessage_fields[9];

/* Maximum encoded size of messages (where known) */
#define WeileConfigMessage_size                  51

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEILECONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
