/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Thu Dec 05 21:22:03 2019. */

#include "config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConfigMessage_fields[9] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ConfigMessage, wifi, wifi, &WifiConfigMessage_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, http, wifi, &HttpConfigMessage_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt, http, &MqttConfigMessage_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, debug, mqtt, &DebugConfigMessage_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, relay, debug, &RelayConfigMessage_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, cover, relay, &CoverConfigMessage_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo, cover, &ZinguoConfigMessage_fields),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, ConfigMessage, module_type, zinguo, 0),
    PB_LAST_FIELD
};

const pb_field_t WifiConfigMessage_fields[7] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, WifiConfigMessage, ssid, ssid, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, pass, ssid, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, WifiConfigMessage, is_static, pass, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, ip, is_static, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, sn, ip, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, WifiConfigMessage, gw, sn, 0),
    PB_LAST_FIELD
};

const pb_field_t HttpConfigMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, HttpConfigMessage, port, port, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, user, port, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, pass, user, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, HttpConfigMessage, ota_url, pass, 0),
    PB_LAST_FIELD
};

const pb_field_t MqttConfigMessage_fields[9] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, MqttConfigMessage, server, server, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, port, server, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, user, port, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, pass, user, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, MqttConfigMessage, retain, pass, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, topic, retain, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, MqttConfigMessage, discovery, topic, 0),
    PB_FIELD(  8, STRING  , SINGULAR, STATIC  , OTHER, MqttConfigMessage, discovery_prefix, discovery, 0),
    PB_LAST_FIELD
};

const pb_field_t DebugConfigMessage_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, DebugConfigMessage, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, DebugConfigMessage, server, type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, DebugConfigMessage, port, server, 0),
    PB_LAST_FIELD
};

const pb_field_t RelayConfigMessage_fields[10] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, RelayConfigMessage, led_type, led_type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_start, led_type, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_end, led_start, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, power_on_state, led_end, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, last_state, power_on_state, 0),
    PB_REPEATED_FIXED_COUNT(  6, UINT32  , OTHER, RelayConfigMessage, study_index, last_state, 0),
    PB_REPEATED_FIXED_COUNT(  7, UINT32  , OTHER, RelayConfigMessage, study, study_index, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_light, study, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, RelayConfigMessage, led_time, led_light, 0),
    PB_LAST_FIELD
};

const pb_field_t CoverConfigMessage_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, CoverConfigMessage, position, position, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, CoverConfigMessage, direction, position, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, CoverConfigMessage, hand_pull, direction, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, CoverConfigMessage, weak_switch, hand_pull, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, CoverConfigMessage, power_switch, weak_switch, 0),
    PB_LAST_FIELD
};

const pb_field_t ZinguoConfigMessage_fields[10] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, ZinguoConfigMessage, dual_motor, dual_motor, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, dual_warm, dual_motor, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, delay_blow, dual_warm, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, linkage, delay_blow, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, max_temp, linkage, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, close_warm, max_temp, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, close_ventilation, close_warm, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, beep, close_ventilation, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, reverse_led, beep, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ConfigMessage, wifi) < 65536 && pb_membersize(ConfigMessage, http) < 65536 && pb_membersize(ConfigMessage, mqtt) < 65536 && pb_membersize(ConfigMessage, debug) < 65536 && pb_membersize(ConfigMessage, relay) < 65536 && pb_membersize(ConfigMessage, cover) < 65536 && pb_membersize(ConfigMessage, zinguo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ConfigMessage_WifiConfigMessage_HttpConfigMessage_MqttConfigMessage_DebugConfigMessage_RelayConfigMessage_CoverConfigMessage_ZinguoConfigMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ConfigMessage, wifi) < 256 && pb_membersize(ConfigMessage, http) < 256 && pb_membersize(ConfigMessage, mqtt) < 256 && pb_membersize(ConfigMessage, debug) < 256 && pb_membersize(ConfigMessage, relay) < 256 && pb_membersize(ConfigMessage, cover) < 256 && pb_membersize(ConfigMessage, zinguo) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ConfigMessage_WifiConfigMessage_HttpConfigMessage_MqttConfigMessage_DebugConfigMessage_RelayConfigMessage_CoverConfigMessage_ZinguoConfigMessage)
#endif


/* @@protoc_insertion_point(eof) */
