/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Dec 03 22:54:23 2019. */

#include "config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConfigMessage_fields[46] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, ConfigMessage, wifi_ssid, wifi_ssid, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, wifi_pass, wifi_ssid, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, dhcp_static, wifi_pass, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, dhcp_ip, dhcp_static, 0),
    PB_FIELD(  7, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, dhcp_sn, dhcp_ip, 0),
    PB_FIELD(  8, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, dhcp_gw, dhcp_sn, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, http_port, dhcp_gw, 0),
    PB_FIELD( 16, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, http_user, http_port, 0),
    PB_FIELD( 17, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, http_pass, http_user, 0),
    PB_FIELD( 18, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, ota_url, http_pass, 0),
    PB_FIELD( 20, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_server, ota_url, 0),
    PB_FIELD( 21, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_port, mqtt_server, 0),
    PB_FIELD( 22, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_user, mqtt_port, 0),
    PB_FIELD( 23, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_pass, mqtt_user, 0),
    PB_FIELD( 24, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_retain, mqtt_pass, 0),
    PB_FIELD( 25, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_topic, mqtt_retain, 0),
    PB_FIELD( 26, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_discovery, mqtt_topic, 0),
    PB_FIELD( 27, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, mqtt_discovery_prefix, mqtt_discovery, 0),
    PB_FIELD( 30, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, debug_type, mqtt_discovery_prefix, 0),
    PB_FIELD( 31, STRING  , SINGULAR, STATIC  , OTHER, ConfigMessage, debug_server, debug_type, 0),
    PB_FIELD( 32, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, debug_port, debug_server, 0),
    PB_FIELD( 40, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, module_type, debug_port, 0),
    PB_FIELD( 41, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_led_type, module_type, 0),
    PB_FIELD( 42, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_led_start, relay_led_type, 0),
    PB_FIELD( 43, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_led_end, relay_led_start, 0),
    PB_FIELD( 44, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_power_on_state, relay_led_end, 0),
    PB_REPEATED_FIXED_COUNT( 45, BOOL    , OTHER, ConfigMessage, relay_last_state, relay_power_on_state, 0),
    PB_REPEATED_FIXED_COUNT( 46, INT32   , OTHER, ConfigMessage, relay_study_index, relay_last_state, 0),
    PB_REPEATED_FIXED_COUNT( 47, INT32   , OTHER, ConfigMessage, relay_study, relay_study_index, 0),
    PB_FIELD( 48, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_led_light, relay_study, 0),
    PB_FIELD( 49, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, relay_led_time, relay_led_light, 0),
    PB_FIELD( 60, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, cover_position, relay_led_time, 0),
    PB_FIELD( 61, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, cover_direction, cover_position, 0),
    PB_FIELD( 62, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, cover_hand_pull, cover_direction, 0),
    PB_FIELD( 63, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, cover_weak_switch, cover_hand_pull, 0),
    PB_FIELD( 64, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, cover_power_switch, cover_weak_switch, 0),
    PB_FIELD( 70, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_dual_motor, cover_power_switch, 0),
    PB_FIELD( 71, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_dual_warm, zinguo_dual_motor, 0),
    PB_FIELD( 72, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_delay_blow, zinguo_dual_warm, 0),
    PB_FIELD( 73, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_linkage, zinguo_delay_blow, 0),
    PB_FIELD( 74, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_max_temp, zinguo_linkage, 0),
    PB_FIELD( 75, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_close_warm, zinguo_max_temp, 0),
    PB_FIELD( 76, INT32   , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_close_ventilation, zinguo_close_warm, 0),
    PB_FIELD( 77, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_beep, zinguo_close_ventilation, 0),
    PB_FIELD( 78, BOOL    , SINGULAR, STATIC  , OTHER, ConfigMessage, zinguo_reverse_led, zinguo_beep, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
